server:
  port: 8080
spring:
  application:
    name: projeto-spring-mvc
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/projeto-frontend
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        jdbc.lob.non_contextual_creation: true
        hbm2ddl:
          auto: update

